sonar.projectKey=my-banking-app_identity-ocr-liveness-kata-node
sonar.organization=my-banking-app
sonar.host.url=https://sonarcloud.io
sonar.branch.name=main

sonar.sources=src

sonar.exclusions=dist/**,node_modules/**,**/*.d.ts,**/mocks/**, **/*.module.ts, **/*.spec.ts,**/*.test.ts,
sonar.test.exclusions=**/*.spec.ts,**/*.test.ts, **/*.module.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info

